# Generated by Django 5.2.17 on 2026-09-15 14:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_telegram_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('service.start', 'Start service'), ('service.stop', 'Stop service'), ('service.restart', 'Restart service'), ('service.logs', 'Read service logs')], max_length=64)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('claimed', 'Claimed'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('actor', models.CharField(max_length=120)),
                ('idempotency_key', models.CharField(blank=True, max_length=120)),
                ('claim_token', models.CharField(blank=True, max_length=64)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='control.server')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['server', 'state', 'created_at'], name='control_ope_server__5163f0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('server', 'actor', 'idempotency_key'), name='uniq_operation_idempotency')],
            },
        ),
    ]
