# Generated by Django 5.2.17 on 2026-09-15 15:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_operations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('requested_ref', models.CharField(max_length=255)),
                ('resolved_commit', models.CharField(blank=True, max_length=40)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('preparing', 'Preparing'), ('cloning', 'Cloning'), ('building', 'Building'), ('releasing', 'Releasing'), ('health_check', 'Health Check'), ('activating', 'Activating'), ('verifying', 'Verifying'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='queued', max_length=20)),
                ('requested_by', models.CharField(max_length=120)),
                ('failure_code', models.CharField(blank=True, max_length=100)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source_deployment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.deployment')),
            ],
            options={
                'ordering': ['-queued_at'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('preparing', 'Preparing'), ('cloning', 'Cloning'), ('building', 'Building'), ('releasing', 'Releasing'), ('health_check', 'Health Check'), ('activating', 'Activating'), ('verifying', 'Verifying'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], max_length=20)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='control.deployment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('exact_commit', models.CharField(max_length=40)),
                ('path', models.CharField(max_length=500)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deployment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='release', to='control.deployment')),
            ],
        ),
        migrations.AddField(
            model_name='deployment',
            name='active_release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_deployments', to='control.release'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='previous_release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollback_deployments', to='control.release'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.SlugField(max_length=80)),
                ('executor', models.CharField(choices=[('systemd', 'Systemd')], default='systemd', max_length=20)),
                ('repository', models.URLField(max_length=500)),
                ('branch', models.CharField(default='main', max_length=255)),
                ('root_directory', models.CharField(default='.', max_length=255)),
                ('runtime', models.CharField(choices=[('node-nextjs', 'Node/Next.js'), ('python-django', 'Python/Django')], max_length=32)),
                ('install_configuration', models.JSONField(blank=True, default=dict)),
                ('build_configuration', models.JSONField(blank=True, default=dict)),
                ('service_port', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='control.project')),
                ('target_server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_services', to='control.server')),
            ],
            options={
                'ordering': ['project__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='release',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='control.service'),
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('path', models.CharField(default='/health', max_length=255)),
                ('expected_status', models.PositiveIntegerField(default=200)),
                ('timeout_seconds', models.PositiveIntegerField(default=10)),
                ('interval_seconds', models.PositiveIntegerField(default=5)),
                ('attempts', models.PositiveIntegerField(default=6)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_check', to='control.service')),
            ],
        ),
        migrations.AddField(
            model_name='deployment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='control.service'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uniq_project_service'),
        ),
        migrations.AddConstraint(
            model_name='release',
            constraint=models.UniqueConstraint(fields=('service', 'name'), name='uniq_service_release'),
        ),
    ]
