# Generated by Django 5.2.17 on 2026-09-15 15:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_deployment_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('key', models.CharField(max_length=128)),
                ('value_type', models.CharField(choices=[('plain', 'Plain'), ('secret', 'Secret')], max_length=10)),
                ('scope', models.CharField(choices=[('project', 'Project'), ('service', 'Service'), ('environment', 'Environment')], max_length=16)),
                ('environment', models.SlugField(blank=True, max_length=80)),
                ('plain_value', models.TextField(blank=True)),
                ('secret_ciphertext', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment_variables', to='control.project')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environment_variables', to='control.service')),
            ],
            options={
                'ordering': ['key'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('scope', 'project')), fields=('project', 'key'), name='uniq_project_variable'), models.UniqueConstraint(condition=models.Q(('scope', 'service')), fields=('service', 'key'), name='uniq_service_variable'), models.UniqueConstraint(condition=models.Q(('scope', 'environment')), fields=('service', 'environment', 'key'), name='uniq_environment_variable')],
            },
        ),
    ]
