# Generated by Django 5.2.17 on 2026-09-15 15:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_environment_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='kind',
            field=models.CharField(choices=[('service.start', 'Start service'), ('service.stop', 'Stop service'), ('service.restart', 'Restart service'), ('service.logs', 'Read service logs'), ('volume.create', 'Create managed volume')], max_length=64),
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.SlugField(max_length=80)),
                ('host_path', models.CharField(max_length=500)),
                ('mount_path', models.CharField(max_length=500)),
                ('owner', models.CharField(max_length=64)),
                ('group', models.CharField(max_length=64)),
                ('mode', models.CharField(default='0750', max_length=4)),
                ('backup_policy', models.CharField(choices=[('none', 'None'), ('daily', 'Daily')], default='none', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='control.project')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='volumes', to='control.server')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='volumes', to='control.service')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('project', 'name'), name='uniq_project_volume')],
            },
        ),
    ]
