# Generated by Django 5.2.17 on 2026-09-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_volumes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='kind',
            field=models.CharField(choices=[('service.start', 'Start service'), ('service.stop', 'Stop service'), ('service.restart', 'Restart service'), ('service.logs', 'Read service logs'), ('volume.create', 'Create managed volume'), ('server.bootstrap', 'Bootstrap server')], max_length=64),
        ),
    ]
