# Generated by Django 5.2.17 on 2026-09-15 15:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_bootstrap_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='kind',
            field=models.CharField(choices=[('service.start', 'Start service'), ('service.stop', 'Stop service'), ('service.restart', 'Restart service'), ('service.logs', 'Read service logs'), ('volume.create', 'Create managed volume'), ('server.bootstrap', 'Bootstrap server'), ('database.create', 'Create database'), ('database.restore', 'Restore database')], max_length=64),
        ),
        migrations.CreateModel(
            name='DatabaseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('database_name', models.CharField(max_length=63)),
                ('username', models.CharField(max_length=63)),
                ('password_ciphertext', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('ready', 'Ready'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('last_backup_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='control.project')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='databases', to='control.server')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='databases', to='control.service')),
            ],
            options={
                'ordering': ['database_name'],
                'constraints': [models.UniqueConstraint(fields=('server', 'database_name'), name='uniq_server_database'), models.UniqueConstraint(fields=('server', 'username'), name='uniq_server_database_user')],
            },
        ),
    ]
