# Generated by Django 5.2.17 on 2026-09-15 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_database_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='kind',
            field=models.CharField(choices=[('service.start', 'Start service'), ('service.stop', 'Stop service'), ('service.restart', 'Restart service'), ('service.logs', 'Read service logs'), ('volume.create', 'Create managed volume'), ('server.bootstrap', 'Bootstrap server'), ('database.create', 'Create database'), ('database.restore', 'Restore database'), ('deployment.deploy', 'Deploy release'), ('deployment.rollback', 'Rollback release')], max_length=64),
        ),
        migrations.CreateModel(
            name='GitHubDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.CharField(max_length=100, unique=True)),
                ('event', models.CharField(max_length=50)),
                ('commit', models.CharField(max_length=40)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_deliveries', to='control.service')),
            ],
        ),
    ]
