# Generated by Django 5.2.17 on 2026-09-15 15:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_deployment_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='kind',
            field=models.CharField(choices=[('service.start', 'Start service'), ('service.stop', 'Stop service'), ('service.restart', 'Restart service'), ('service.logs', 'Read service logs'), ('volume.create', 'Create managed volume'), ('server.bootstrap', 'Bootstrap server'), ('database.create', 'Create database'), ('database.restore', 'Restore database'), ('deployment.deploy', 'Deploy release'), ('deployment.rollback', 'Rollback release'), ('domain.configure', 'Configure domain'), ('domain.ssl', 'Enable domain SSL')], max_length=64),
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('hostname', models.CharField(max_length=253, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('configured', 'Configured'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('ssl_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='control.project')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domains', to='control.server')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domains', to='control.service')),
            ],
            options={
                'ordering': ['hostname'],
            },
        ),
    ]
