# Generated by Django 5.2.17 on 2026-09-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0015_controlled_takeover'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='progress',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='operation',
            name='progress_sequence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
