# Generated by Django 5.2.17 on 2026-09-30 08:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0016_operation_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='platform_managed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='operation',
            name='kind',
            field=models.CharField(choices=[('service.provision', 'Provision service'), ('service.start', 'Start service'), ('service.stop', 'Stop service'), ('service.restart', 'Restart service'), ('service.logs', 'Read service logs'), ('volume.create', 'Create managed volume'), ('server.bootstrap', 'Bootstrap server'), ('database.create', 'Create database'), ('database.restore', 'Restore database'), ('deployment.deploy', 'Deploy release'), ('deployment.rollback', 'Rollback release'), ('domain.configure', 'Configure domain'), ('domain.ssl', 'Enable domain SSL'), ('service.takeover.prepare', 'Prepare controlled service takeover'), ('service.takeover.activate', 'Activate controlled service takeover')], max_length=64),
        ),
        migrations.AlterField(
            model_name='service',
            name='lifecycle_state',
            field=models.CharField(choices=[('pending', 'Pending provisioning'), ('provisioning', 'Provisioning'), ('provision_failed', 'Provisioning failed'), ('adopted', 'Adopted'), ('configured', 'Configured'), ('managed', 'Managed')], default='managed', max_length=16),
        ),
        migrations.CreateModel(
            name='ServiceProvisioning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('configuration', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deployment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='control.deployment')),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='control.operation')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provisionings', to='control.service')),
            ],
        ),
    ]
