# Generated by Django 5.2.17 on 2026-10-06 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0021_variable_target_domain_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoolifyManagedApplication',
            fields=[
                ('request_id', models.UUIDField(primary_key=True, serialize=False)),
                ('application_uuid', models.CharField(max_length=80, null=True, unique=True)),
                ('target', models.CharField(max_length=80)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.serviceprincipal')),
            ],
        ),
    ]
